name: PushOrPull
on: [push, pull_request]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Is it a push ?
        if: ${{ github.event_name == 'push' }}
        run: echo "It's a push"
      - name: It's not a push
        if: ${{ github.event_name != 'push' }}
        run: echo "It's a not a push"
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Is it a pull ?
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "It's a pull request"
      - name: It's not a pull ?
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "It's not a pull request"

# autre méthode
# name: Push or Pull ?
# on: [push, pull_request]

# env:
#   PUSH: C'est un Push !
#   PULL_REQUEST: C'est une PR !

# jobs:
#   push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Push
#         run: echo "$PUSH"

#   pull_request:
#     runs-on: unbuntu-latest
#     if: ${{ github.event_name == 'pull_request'}}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: pull request
#         run: echo "$PR"