name: PushOrPull
on: [push, pull_request]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Is it a push ?
        if: ${{ github.event_name == 'push' }}
        run: echo "It's a push"
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Is it a pull ?
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "It's a pull request"
